NUMPY-used for array
............ndarray-n dimensional array

In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy
arr = numpy.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


1) - 0D array/scaler array

In [ ]:
#0d array
import numpy
a = numpy.array(90)
print(a)
print(type(a))

90
<class 'numpy.ndarray'>


In [ ]:
#1d array
import numpy as np
b =np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [ ]:
#2d array
import numpy as np
b =np.array()
print(b)

In [ ]:
#3d array
import numpy as np
b =np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[5,6,7,8]]])
print(b)

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [ ]:
#dimension of an array
import numpy as np
a = np.array(12)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2],[3,4]],[[1,2,],[1,2,]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#3d array
import numpy as np
d = np.array([[[1,2,7],[12,9,3]],[[3,1,2],[1,2,9]]])
print(d)
print(d[0,1,2])
print(d[1,1,0])
print(d[1,0,2])

[[[ 1  2  7]
  [12  9  3]]

 [[ 3  1  2]
  [ 1  2  9]]]
3
1
2


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::])
print(arr[2:5])

[1 2 3 4 5 6 7]
[3 4 5]


In [ ]:
#copy and view
import numpy as np
a=np.array([1,2,3,4])
x = a.copy()
a[2]=90
print(a)
print(x)

[ 1  2 90  4]
[1 2 3 4]


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
x = a.view()
print(a)
print(x)

[1 2 3 4]
[1 2 3 4]


In [ ]:
import numpy as np
d = np.array([[[1,2,7],[12,9,3]],[[3,1,2],[1,2,9]]])
print(d.shape)

(2, 2, 3)


In [ ]:
import numpy as np
d = np.array([[[1,2,7],[12,9,3],[1,2,3]],[[56,7,8],[3,1,2],[1,2,9]]])
print(d.shape)

(2, 3, 3)


In [ ]:
#reshaping
import numpy as np
d = np.array([[[1,2,7],[12,9,3]],[[3,1,2],[1,2,9]]])
n = d.reshape(6,2)
print(n)

[[ 1  2]
 [ 7 12]
 [ 9  3]
 [ 3  1]
 [ 2  1]
 [ 2  9]]


In [ ]:
a = np.array([1,2,3,4,5,56,67,78,89,10,11,12])
n = a.reshape(4,3)
print(n)

[[ 1  2  3]
 [ 4  5 56]
 [67 78 89]
 [10 11 12]]


In [ ]:
#1d to 3d
a = np.array([1,2,3,4,5,56,67,78,89,10,11,12])
n = a.reshape(3,2,2)
print(n)

[[[ 1  2]
  [ 3  4]]

 [[ 5 56]
  [67 78]]

 [[89 10]
  [11 12]]]


In [ ]:
#numpy and iterating
a = np.array([1,2,3,4])
for i in a:
  print(i)

1
2
3
4


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
for i in a:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
#nditer
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(a):
  print(i)


1
2
3
4
5
6


In [ ]:
#concatinate method
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
arr = np.concatenate((a,b))
print(arr)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
arr = np.concatenate((a,b),axis =1)
print(arr)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
#numpy splitting array : array_split()
import numpy as np
a = np.array([1,2,3,4,5,6])
new_a = np.split(a,6)
print(new_a)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
#where operation
import numpy as np
a = np.array([1,2,3,4,5,6])
x= np.where(a==1)
print(x)

(array([0]),)


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
x = np.where(a%2==1)
print(x)

(array([0, 2, 4]),)


In [ ]:
#sorting array
import numpy as np
a = np.array([1,2,3,41,5,6])
print(np.sort(a))

[ 1  2  3  5  6 41]


In [ ]:
import numpy as np
a = np.array([1,2,23,4,55,6])
y = np.where(a==2)
print(y)
x = np.searchsorted(a,2)
print(x)

(array([1]),)
1


In [ ]:
#numpy filter array
#return only true value
import numpy as np
a = np.array([1,2,3,4,5,6])
x = a[[True,False,False,True,False,True]]
print(x)

[1 4 6]


In [ ]:
a = np.array([13,45,65,72])
filter_a=[]
for i in a:
  if i>40:
    filter_a.append(True)
  else:
    filter_a.append(False)
new_a = a[filter_a]
print(filter_a)
print(new_a)

[False, True, True, True]
[45 65 72]


In [ ]:
#Numpy array use np.zeros
z = np.empty(4)
z

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [ ]:
#identity operator
z =np. identity(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#array methods
a = np.array((4,3,2,1))
a.sum()
a.max()
a.argmax()
a.cumsum()
a.cumprod()
a.var()
a.std()
a.shape = (2,2)
a.T

array([[4, 2],
       [3, 1]])